---

##################################################################################################

- hosts: webserver-nodes
  gather_facts: no

  roles:
    - bootstrap

##################################################################################################

- hosts: webserver-nodes
  become: true

  roles:
    - application

##################################################################################################
